
(* Entry point for program *)
program = {expression} EOF;

(* The last expression in a list is the returned value *)
expression = atom
           | "(" {expression} ")"
           | "(" unary expression ")"
           | "(" binary expression expression ")"
           | "(" ifExpression ")"
           | "(" letExpression ")"
           | "(" defExpression ")" ;

atom = NUMBER
     | STRING
     | IDENTIFIER ;

ifExpression = "if" expression expression {"else" "if" expression expression} {"else" expression} ;

letExpression = "let" IDENTIFIER {expression} ;

defExpression = "def" IDENTIFIER {expression} ;