
(* Entry point for program *)
program = expression*, EOF;

(* The last expression in a list is the returned value *)
expression = atom
           | "(", {expression}, ")"
           | "(", unary expression, ")"
           | "(", binary expression expression, ")";

atom = NUMBER
     | STRING;